name: ihydrocal
channels:
  - conda-forge

dependencies:
  - python=3.13
  - numpy
  - pandas
  - matplotlib-base
  - scipy
  - pyyaml
  - openpyxl
  - pytest
  - black
  - flake8
  - git
  - pip
  - pip:
    - build
    - twine
    - flopy
    - pyemu
    - tqdm
    - termcolor
    - ipykernel
    - jupyterlab
    - nbconvert
    - debugpy
    - -e .